# gaussian
python experiment.py --exp-name detection_gaussian_noise0_095 --idx-range 0 100 --est-strat gaussian_noise --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.095 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# poisson
python experiment.py --exp-name detection_poisson_noise0_0065 --idx-range 0 100 --est-strat poisson_noise --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.0065--max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# brightness very high distortion
python experiment_fast.py --exp-name detection_brightness0_203_sigma0_21 --idx-range 0 100 --est-strat brightness --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.203 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 0.21 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# pixel_scale very higih distortion
python experiment_fast.py --exp-name detection_pixel_scale0_384_sigma0_21 --idx-range 0 100 --est-strat pixel_scale --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.384 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 0.21 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# rotate
python experiment.py --exp-name detection_rotate0_0407_sigma0_1 --idx-range 0 100 --est-strat rotate --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 50 --exp-param-2 strat-param --exp-param-range-2 0.0407 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 0.1 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# crop_resize
python experiment.py --exp-name detection_crop_resize0_0904_sigma0_1 --idx-range 0 100 --est-strat crop_resize --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 50 --exp-param-2 strat-param --exp-param-range-2 0.0904 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 0.1 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# contrast
python experiment.py --exp-name detection_contrast0_77_sigma0_1 --idx-range 0 100 --est-strat contrast --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 --exp-param-2 strat-param --exp-param-range-2 0.79 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 0.1 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4