# brightness
python experiment.py --exp-name detection_brightness0_09 --est-strat brightness --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.09 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# uniform
python experiment.py --exp-name detection_uniform0_064 --est-strat uniform --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.064 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# translate
python experiment.py --exp-name detection_translate0_45 --est-strat translate --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.45 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# rotate
python experiment.py --exp-name detection_rotate0_018 --est-strat rotate --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.018 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# pixel_scale
python experiment.py --exp-name detection_pixel_scale0_17 --est-strat pixel_scale --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.17 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# crop_resize
python experiment.py --exp-name detection_crop_resize0_04 --est-strat crop_resize --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.04 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# contrast
python experiment.py --exp-name detection_contrast0_55 --est-strat contrast --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.55 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# gaussian
python experiment.py --exp-name detection_gaussian_noise0_095 --est-strat gaussian_noise --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.095 --max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
# poisson
python experiment.py --exp-name detection_poisson_noise0_0065 --est-strat poisson_noise --exp-param zero-iters --num-exp-per-param 100 --img-idxs image_idxs.npz --exp-param-range 2 50 --exp-param-2 strat-param --exp-param-range-2 0.0065--max-queries 100000 --top-k 1 --img-index 0 --out-dir ./out_label_only --adv-thresh 0.15 --sigma 1e-3 --plateau-length 20 --samples-per-draw 100 --batch-size 4 --min-lr 1e-4 --label-only --zero-iters 50 --label-only-sigma 0.032 --conservative 4
